@startuml(id=SYSTEMBOOKINGTOSCHEDULESINTERNET-SystemContext)
title SYSTEM BOOKING TO SCHEDULES INTERNET - System Context

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<2>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<3>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<4>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam rectangle<<5>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
rectangle "==Admin\n<size:10>[Person]</size>\n\nA manager who manages the project's operations." <<1>> as 1
rectangle "==Customer\n<size:10>[Person]</size>\n\nA person users website of booking schedule  medical examine ." <<2>> as 2
rectangle "==Doctor\n<size:10>[Person]</size>\n\nA person with a medical degree whose job is to treat." <<3>> as 3
rectangle "==E-mail System\n<size:10>[Software System]</size>\n\nThe internet Microsoft Exchange e-mail system." <<4>> as 4
rectangle "==SYSTEM BOOKING TO SCHEDULES INTERNET\n<size:10>[Software System]</size>" <<5>> as 5
1 .[#707070,thickness=2].> 5 : "Uses"
2 .[#707070,thickness=2].> 5 : "Uses"
3 .[#707070,thickness=2].> 5 : "Uses"
4 .[#707070,thickness=2].> 1 : "Sends e-mail to"
4 .[#707070,thickness=2].> 2 : "Sends e-mail to"
4 .[#707070,thickness=2].> 3 : "Sends e-mail to"
5 .[#707070,thickness=2].> 4 : "Sends e-mail using"
@enduml